# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Beer < Formula
  desc "CLI for managing your JIRA / Gerrit / git workflow."
  homepage "https://github.com/kunickiaj/beer"
  version "0.6.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kunickiaj/beer/releases/download/v0.6.1/beer_0.6.1_darwin_x86_64.tar.gz"
      sha256 "0a8ef69b37e4fb6ec2f89fb3f9a9ebcbf64ec199047b29fddbaacfe0033138b6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kunickiaj/beer/releases/download/v0.6.1/beer_0.6.1_Linux_x86_64.tar.gz"
      sha256 "725525707db1300e4b71a4d2d9b33fb8f6d867a1b43b70e57e5230d0552ee9c0"
    end
  end

  def install
    bin.install "beer"
  end

  test do
    system "#{bin}/beer --help"
  end
end
